### ISSUE TITLE
Support LDAP Referral

### ISSUE THREAD

**Issue by phillipjohnson** [Haulmont/jmix-ldap#14]
It looks like someone has already considered this possibility:

https://github.com/Haulmont/jmix-ldap/blob/master/ldap/src/main/java/io/jmix/ldap/LdapConfiguration.java#L60

```java
// contextSource.setReferral("follow"); todo property?
```

This would be a helpful feature to support for organizations with multiple domain controllers linked to a root controller via referral.

**Comment by GlebDurygin** [comment]
### Solution
The `jmix.ldap.manager-referral` property without default value has been added.

### QA
Check that the user can set the property value
